### ISSUE TITLE
Whether fusion-plus branch for fusion plus mode is ready ?

### ISSUE THREAD

**Issue by sh7ning** [1inch/1inch-sdk-go#85]
I want to quote and place order in fusion plus mode, and I found the fusion-plus branch: https://github.com/1inch/1inch-sdk-go/tree/fusion-plus ,

I want to confirm whether https://github.com/1inch/1inch-sdk-go/tree/fusion-plus for fusion plus mode is ready for quote and place order ?

Intent Swap (Fusion mode) does not seem to support cross-chain swaps .

**Comment by Tanz0rz** [comment]
Fusion mode is for same-chain swaps only

Fusion+ is specifically designed for cross-chain swaps. That branch will work if you want to use it now, but it is still actively in development, so consider it an alpha/beta branch.

**Comment by sh7ning** [comment]
Thank you.

By the way, are there other language repositories for reference?
