### ISSUE TITLE
fusion api client.GetQuote() response unmarshalJson failed

### ISSUE THREAD

**Issue by sh7ning** [1inch/1inch-sdk-go#87]
I call fusion api swap ETH to USDC on the ETH chain , but the interface call failed when EnableEstimate is true

```
response, err := client.GetQuote(ctx, fusion.QuoterControllerGetQuoteParamsFixed{
    FromTokenAddress: fromTokenAddress,
    ToTokenAddress:   toTokenAddress,
    Amount:           amount,
    WalletAddress:    publicAddress,
    EnableEstimate:   true, // false is ok, true will unmarshal failed
})
```

failed to request: processing response failed: json: cannot unmarshal string into Go struct field PresetClass.presets.fast.exclusiveResolver of type map[string]interface {}

I found the response body exclusiveResolver is string or null, but struct is map[string]interface {}

api doc:  https://portal.1inch.dev/documentation/apis/swap/intent-swap/swagger/quoter?method=get&path=%2Fv2.0%2F1%2Fquote%2Freceive

example: https://github.com/1inch/1inch-sdk-go/blob/main/sdk-clients/fusion/examples/place_order/main.go#L50

**Comment by Tanz0rz** [comment]
Testing with local addresses does not give me this error.

If you are able to recreate the error with non-sensitive addresses, please post them here.

If you are able to share the exact request that caused this privately, please send the data here: sdk.debug.throttle958@dralias.com

**Comment by sh7ning** [comment]
you can try with replace const part of [example: https://github.com/1inch/1inch-sdk-go/blob/main/sdk-clients/fusion/examples/place_order/main.go#L19]() like this:

```
const (
	usdc    = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" // eth contract addr
	wmatic  = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" // usdc contract addr on eth
	amount  = "100000000000000000" // 0.01 eth
	chainId = constants.EthereumChainId // 1
)
```

**Comment by Tanz0rz** [comment]
What version of Go are you using? Are you running these examples on a locally cloned `main` branch on your machine?

**Comment by sh7ning** [comment]
What version of Go are you using? 
go version go1.23.1 darwin/arm64

Are you running these examples on a locally cloned main branch on your machine?
yes


https://github.com/1inch/1inch-sdk-go/blob/main/sdk-clients/fusion/fusion_quoter_types.gen.go#L78
I guess the response body is the result of the server. The exclusiveResolver field is defined string cannot be parsed using map of any version of go. Both the main branch and the fusionplus branch use map type.

**Comment by Tanz0rz** [comment]
I tried again and was able to reproduce it. This is a fix built off of the `main` branch. Pull this and use it for now: `fix/fusion-quote-exclusive-resolvers`

**Comment by sh7ning** [comment]
Thank you for your help.

**Comment by Tanz0rz** [comment]
#90 merged
